[package]
org = "ballerina"
name = "time"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["time", "utc", "epoch", "civil"]
repository = "https://github.com/ballerina-platform/module-ballerina-time"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "time-native"
version = "@toml.version@"
path = "../native/build/libs/time-native-@project.version@.jar"
